# Generated by Django 4.1.1 on 2022-09-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Delivery',
        ),
    ]
