# Generated by Django 4.1.1 on 2022-09-30 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderList', '0002_rename_orders_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='table_row_index',
            new_name='sheet_num',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='table_row_number',
        ),
    ]
