# Generated by Django 4.1.1 on 2022-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderList', '0003_rename_table_row_index_delivery_sheet_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='cost_rub',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='cost_usd',
            field=models.FloatField(),
        ),
    ]
